spring:
  profiles:
    active:
      - dog
      - EN
      - prod

by:
  username: YmlUsername
  password: YmlPassword
  jdbcurl: YmlJdbcUrl

---
spring:
  profiles: prod

by:
  username: YmlProdUsername
  password: YmlProdPassword
  jdbcurl: YmlProdJdbcUrl